title: Henry Osei
description: Hello! Welcome to my portfolio. I recently graduated with my M.S. in Applied Geospatial Science and I enjoy all things remote sensing, GIS, and environmental monitoring.
theme: jekyll-theme-slate
